### ISSUE TITLE
Pagina publica - nosotros

### ISSUE THREAD

**Issue by facundo1000** [facundo1000/laboratorio-mangement-front#4]
## Objetivo principal:
1. Crear la pagina nosotros tomando como referencia el mock en [figma](https://www.figma.com/file/Q8uOaHmjzb9VNpM7iU7hio/Proyecto-An%C3%A1lisis-Cl%C3%ADnicos?type=design&node-id=946-704&mode=design&t=y9oe94Ypp0dK3Q5U-4).
2. Crear la relacion entre la pagina y el botón "nosotros" en el navbar. Cambiar por la que dice "institucion".

**Comment by ignaciorossetto** [comment]
done

**Comment by ignaciorossetto** [comment]
done
